config/routes.rb
Dbros::Application.routes.draw do

  resources :unions

  resources :magazines

  resources :dossiers

  resources :fascicles

  resources :names

  resources :groups

  resources :areas

  resources :ambits

  resources :names do
	get "names/index"
  end

  get "home/index"

  root 'home#index'

end

app/models/union.rb
class Union < ActiveRecord::Base
  belongs_to :area
  has_and_belongs_to_many :unions
end

app/controllers/unions_controller.rb
class UnionsController < ApplicationController
  before_action :set_union, only: [:show, :edit, :update, :destroy]

  # GET /unions
  # GET /unions.json
  def index
    @unions = Union.all
  end

  # GET /unions/1
  # GET /unions/1.json
  def show
  end

  # GET /unions/new
  def new
    @union = Union.new
  end

  # GET /unions/1/edit
  def edit
	@area = @union.area
  end

  # POST /unions
  # POST /unions.json
  def create
    @union = Union.new(union_params)

    respond_to do |format|
      if @union.save
        format.html { redirect_to @union, notice: 'Union was successfully created.' }
        format.json { render action: 'show', status: :created, location: @union }
      else
        format.html { render action: 'new' }
        format.json { render json: @union.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unions/1
  # PATCH/PUT /unions/1.json
  def update
    respond_to do |format|
      if @union.update(union_params)
        format.html { redirect_to @union, notice: 'Union was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @union.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unions/1
  # DELETE /unions/1.json
  def destroy
    @union.destroy
    respond_to do |format|
      format.html { redirect_to unions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_union
      @union = Union.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def union_params
      params.require(:union).permit(:denominazione, :sede, :area_id, :descrizione)
    end
end

app/helpers/unions_helper.rb
module UnionsHelper
end

app/views/unions/_form.html.erb
<%= form_for(@union) do |f| %>
  <% if @union.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@union.errors.count, "error") %> prohibited this union from being saved:</h2>

      <ul>
      <% @union.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :denominazione %><br>
    <%= f.text_field :denominazione %>
  </div>
  <div class="field">
    <%= f.label :sede %><br>
    <%= f.text_field :sede %>
  </div>
  <div class="field">
    <%= f.label :area_id %><br>
    <%= f.collection_select :area_id, Area.all, :id, :area_criminale, :include_blank=>true, :prompt =>'select area crim.' %>
  </div>>
  <div class="field">
    <%= f.label :descrizione %><br>
    <%= f.text_area :descrizione %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unions/edit.html.erb
<h1>Editing union</h1>

<%= render 'form' %>

<%= link_to 'Show', @union %> |
<%= link_to 'Back', unions_path %>

app/views/unions/index.html.erb
<h1>Listing unions</h1>

<table>
  <thead>
    <tr>
      <th>Denominazione</th>
      <th>Sede</th>
      <th>Area</th>
      <th>Descrizione</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @unions.each do |union| %>
      <tr>
        <td><%= union.denominazione %></td>
        <td><%= union.sede %></td>
        <td><%= union.area %></td>
        <td><%= union.descrizione %></td>
        <td><%= link_to 'Show', union %></td>
        <td><%= link_to 'Edit', edit_union_path(union) %></td>
        <td><%= link_to 'Destroy', union, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Union', new_union_path %>

app/views/unions/new.html.erb
<h1>New union</h1>

<%= render 'form' %>

<%= link_to 'Back', unions_path %>

app/views/unions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Denominazione:</strong>
  <%= @union.denominazione %>
</p>

<p>
  <strong>Sede:</strong>
  <%= @union.sede %>
</p>

<p>
  <strong>Area:</strong>
  <%= @union.area.area_criminale %>
</p>

<p>
  <strong>Descrizione:</strong>
  <%= @union.descrizione %>
</p>

<%= link_to 'Edit', edit_union_path(@union) %> |
<%= link_to 'Back', unions_path %>