config/routes.rb
Dbros::Application.routes.draw do

  resources :unions

  resources :magazines

  resources :dossiers

  resources :fascicles

  resources :names

  resources :groups

  resources :areas

  resources :ambits

  resources :names do
	get "names/index"
  end

  get "home/index"

  root 'home#index'

end

app/models/ambit.rb
class Ambit < ActiveRecord::Base
	has_many :names

end

app/controllers/ambits_controller.rb
class AmbitsController < ApplicationController
  before_action :set_ambit, only: [:show, :edit, :update, :destroy]

  # GET /ambits
  # GET /ambits.json
  def index
    @ambits = Ambit.all
  end

  # GET /ambits/1
  # GET /ambits/1.json
  def show
  end

  # GET /ambits/new
  def new
    @ambit = Ambit.new
  end

  # GET /ambits/1/edit
  def edit
  end

  # POST /ambits
  # POST /ambits.json
  def create
    @ambit = Ambit.new(ambit_params)

    respond_to do |format|
      if @ambit.save
        format.html { redirect_to @ambit, notice: 'Ambit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ambit }
      else
        format.html { render action: 'new' }
        format.json { render json: @ambit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ambits/1
  # PATCH/PUT /ambits/1.json
  def update
    respond_to do |format|
      if @ambit.update(ambit_params)
        format.html { redirect_to @ambit, notice: 'Ambit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ambit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ambits/1
  # DELETE /ambits/1.json
  def destroy
    @ambit.destroy
    respond_to do |format|
      format.html { redirect_to ambits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ambit
      @ambit = Ambit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ambit_params
      params.require(:ambit).permit(:ambito_criminale, :note_ambito)
    end
end

app/helpers/ambits_helper.rb
module AmbitsHelper
end

app/views/ambits/_form.html.erb
<%= form_for(@ambit) do |f| %>
  <% if @ambit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ambit.errors.count, "error") %> prohibited this ambit from being saved:</h2>

      <ul>
      <% @ambit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ambito_criminale %><br>
    <%= f.text_field :ambito_criminale %>
  </div>
  <div class="field">
    <%= f.label :note_ambito %><br>
    <%= f.text_area :note_ambito %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ambits/edit.html.erb
<h1>Editing ambit</h1>

<%= render 'form' %>

<%= link_to 'Show', @ambit %> |
<%= link_to 'Back', ambits_path %>

app/views/ambits/index.html.erb
<h1>Listing ambits</h1>

<table>
  <thead>
    <tr>
      <th>Ambito criminale</th>
      <th>Note ambito</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ambits.each do |ambit| %>
      <tr>
        <td><%= ambit.ambito_criminale %></td>
        <td><%= ambit.note_ambito %></td>
        <td><%= link_to 'Show', ambit %></td>
        <td><%= link_to 'Edit', edit_ambit_path(ambit) %></td>
        <td><%= link_to 'Destroy', ambit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ambit', new_ambit_path %>

app/views/ambits/new.html.erb
<h1>New ambit</h1>

<%= render 'form' %>

<%= link_to 'Back', ambits_path %>

app/views/ambits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ambito criminale:</strong>
  <%= @ambit.ambito_criminale %>
</p>

<p>
  <strong>Note ambito:</strong>
  <%= @ambit.note_ambito %>
</p>

<%= link_to 'Edit', edit_ambit_path(@ambit) %> |
<%= link_to 'Back', ambits_path %>