config/routes.rb
Dbros::Application.routes.draw do

  resources :unions

  resources :magazines

  resources :dossiers

  resources :fascicles

  resources :names

  resources :groups

  resources :areas

  resources :ambits

  resources :names do
	get "names/index"
  end

  get "home/index"

  root 'home#index'

end

app/models/ambit.rb
class Ambit < ActiveRecord::Base
	has_many :names

end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :names
end

app/models/dossier.rb
class Dossier < ActiveRecord::Base

  has_and_belongs_to_many :names


has_attached_file :documento, 
    :url  => "/assets/dossiers/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/dossiers/:id/:style/:basename.:extension"
    
    validates_attachment_presence :documento


end

app/models/fascicle.rb
class Fascicle < ActiveRecord::Base
  has_and_belongs_to_many :names
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :magazines
  has_and_belongs_to_many :unions
  
    validates_uniqueness_of :numero, :case_sensitive => false, :message => ":  nome già presente!"
    validates_presence_of :numero, :message => ":  campo vuoto!"
  
  def self.search(search, page)
    paginate :per_page => 25, :page => page,
             :conditions => ['numero LIKE ? or note LIKE ? ', "#{search}","%#{search}%"],
             :order => 'numero DESC'
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :names
	  has_and_belongs_to_many :fascicle
end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
  belongs_to :area
  belongs_to :union
  belongs_to :group

has_and_belongs_to_many :fascicles
end

app/models/name.rb
class Name < ActiveRecord::Base
  belongs_to :ambit
  belongs_to :area
  belongs_to :group

  has_and_belongs_to_many :fascicles
  has_and_belongs_to_many :dossiers




  has_attached_file :photo, 
	:styles => { :medium => "300x300>", :thumb => "100x100>" }, 
	:default_url => "/assets/missing_thum.png", 
	:url  => "/assets/avatar/:id/:style/:basename.:extension", 
	:path => ":rails_root/public/assets/avatar/:id/:style/:basename.:extension"

 def self.search(search)
   if search
      find(:all, :conditions => ['cognome_nome LIKE ? or luogo_nascita LIKE ? or data_nascita LIKE ? or residenza LIKE ?', "%#{search}%","%#{search}%",
          "%#{search}%", "%#{search}%",], :order => 'cognome_nome ASC')
    else
     find(:all, :order => 'cognome_nome ASC')
    end
 end



 




end

app/models/union.rb
class Union < ActiveRecord::Base
  belongs_to :area
  has_and_belongs_to_many :unions
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @ambit = @area.ambit
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render action: 'show', status: :created, location: @area }
      else
        format.html { render action: 'new' }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:area_criminale, :note_area, :ambit_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/ambits_helper.rb
module AmbitsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/dossiers_helper.rb
module DossiersHelper
end

app/helpers/fascicles_helper.rb
module FasciclesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/unions_helper.rb
module UnionsHelper
end

app/views/layouts/_side.html.erb
  <div id="container">  
  
    <% flash.each do |name, msg| %>  
      <%= content_tag :div, msg, :id => "flash_#{name}" %>  
    <% end %>  
  
    <div id="side">  
      <strong>Pages</strong>  
      <ul>  
        <li><%= link_to "Home", root_path %></li>  
        <li><%= link_to "Anagrafica", names_path %></li>
		<li><%= link_to "Documenti", dossiers_path %></li>
		<li><%= link_to "Pubblicazioni", magazines_path %></li>
		<li><%= link_to "Società", unions_path %></li>
		<li><%= link_to "Documenti", dossiers_path %></li>
		<li><%= link_to "Fascicoli", fascicles_path %></li>
		<li><%= link_to "Ass. Crim.", groups_path %></li>
		<li><%= link_to "Area Crim.", areas_path %></li>
		<li><%= link_to "Ambito Crim.", ambits_path %></li>
  
      </ul>  
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dbros" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Dbros  </a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>






    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span2">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
        		<li><%= link_to "Home", root_path %></li>  
        		<li><%= link_to "Anagrafica", names_path %></li>
				<li><%= link_to "Documenti", dossiers_path %></li>
				<li><%= link_to "Pubblicazioni", magazines_path %></li>
				<li><%= link_to "Società", unions_path %></li>
				<li><%= link_to "Documenti", dossiers_path %></li>
				<li><%= link_to "Fascicoli", fascicles_path %></li>
				<li><%= link_to "Ass. Crim.", groups_path %></li>
				<li><%= link_to "Area Crim.", areas_path %></li>
				<li><%= link_to "Ambito Crim.", ambits_path %></li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>